# pull official base image
FROM python:slim


# set work directory
WORKDIR /usr/src/app

# install dependencies
RUN pip install numpy scipy spacy pandas
RUN python -m spacy download en_core_web_sm

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# copy project
COPY . /usr/src/app/

# add template folder
ADD ./project/templates /usr/src/app/templates